import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from .models import Base

# By default point to the DB generated by phase 1, which sits in phase1_data_foundation
DB_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'phase1_data_foundation', 'phase1_data.db'))
DATABASE_URI = os.getenv('DATABASE_URI', f'sqlite:///{DB_PATH}')

engine = create_engine(DATABASE_URI)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def init_db():
    Base.metadata.create_all(bind=engine)
